apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: example-go-
spec:
  pipelineRef:
    name: build-and-deploy-pipeline
  params:
    - name: gitUrl
      value: https://github.com/nambrosini/example-go
    - name: gitRevision
      value: HEAD
    - name: imageUrl
      value: registry.localhost:5555/example-go
    - name: imageTag
      value: "1.0"
  workspaces:
    - name: git-source
      persistentVolumeClaim:
        claimName: example-go-source-pvc